### ISSUE TITLE
Toolchina requirements?

### ISSUE THREAD

**Issue by VanushVaswani** [mozilla/dxr#622]
I understand this plugin is tilted towards Mozilla development, but it isn't clear what the toolchain requirements are.

We use GCC and haven't tested building with clang. And further, it's an embedded toolchain.
Would we have to get clang builds working to make use of this tool?

**Comment by erikrose** [comment]
https://dxr.readthedocs.io/en/latest/getting-started.html?highlight=clang#configuration talks a little about toolchain and the reason for requiring clang.

You're welcome to build with GCC, but, unless you use clang, you won't get the symbolic features of DXR for C++, since our symbolic info is extracted by means of a clang-specific compiler plugin. This doesn't mean your production builds need to use clang, of course. Ours don't. But it does need to be built under clang for indexing.
